module.exports = {
  plugins: {
    'postcss-sorting': {
      order: [
        'custom-properties',
        'dollar-variables',
        {
          type: 'at-rule',
          name: 'include',
        },
        {
          type: 'at-rule',
          name: 'include',
          hasBlock: true,
        },
        'declarations',
        {
          type: 'at-rule',
          name: 'media',
        },
      ],
      'properties-order': [
        'position',
        'top',
        'right',
        'bottom',
        'left',
        'display',
        'content',
        'flex',
        'flex-direction',
        'flex-flow',
        'flex-basis',
        'flex-wrap',
        'flex-grow',
        'flex-shrink',
        'justify-content',
        'align-items',
        'align-content',
        'grid',
        'grid-template',
        'grid-template-columns',
        'grid-auto-columns',
        'grid-template-rows',
        'grid-auto-rows',
        'grid-template-areas',
        'grid-auto-flow',
        'grid-gap',
        'order',
        'max-height',
        'min-height',
        'height',
        'max-width',
        'min-width',
        'width',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'font',
        'font-family',
        'font-size',
        'font-weight',
        'line-height',
        'color',
        'letter-spacing',
        'background',
        'background-image',
        'background-color',
        'background-position',
        'background-size',
        'background-repeat',
        'background-origin',
        'background-clip',
        'border',
        'border-radius',
        'outline',
        'transform',
        'transform-style',
        'transition',
        'transition-property',
        'transition-duration',
        'transition-timing-function',
        'transition-delay',
        'animation',
        'animation-name',
        'animation-duration',
        'animation-timing-function',
        'animation-delay',
        'animation-iteration-count',
        'animation-direction',
        'animation-fill-mode',
        'animation-play-state',
      ],
      'unspecified-properties-position': 'bottom',
    },
  },
};
